allowBuilds:
  cypress: true
  esbuild: true
  protobufjs: false
  unrs-resolver: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@verdaccio/*'
  - '@verdaccio-scope/*'
  - 'verdaccio-*'
  # Renovate security update: vite@8.0.5
  - vite@8.0.5
saveExact: true
ignoreScripts: true
preferFrozenLockfile: true
