storage: /verdaccio/storage

plugins: /verdaccio/plugins

store:
  aws-s3-storage:
    bucket: AWS_S3_BUCKET
    keyPrefix: AWS_S3_KEY_PREFIX
    region: AWS_DEFAULT_REGION
    endpoint: AWS_S3_ENDPOINT
    s3ForcePathStyle: true
    accessKeyId: AWS_ACCESS_KEY_ID
    secretAccessKey: AWS_SECRET_ACCESS_KEY
    dynamoTableName: AWS_DYNAMO_TABLE_NAME
    dynamoEndpoint: AWS_DYNAMO_ENDPOINT

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs

log:
  - {type: stdout, format: pretty, level: trace}

listen:
  - 0.0.0.0:4873

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
